repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: master
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: master
    hooks:
      - id: dockerfilelint

  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: master
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/asottile/add-trailing-comma
    rev: master
    hooks:
      - id: add-trailing-comma
