language: node_js
node_js:
  - lts/*
services:
  - docker
before_install:
  - docker build -t stevenpilger/frontend-test -f Dockerfile --target build .
  - docker run -it --rm stevenpilger/frontend-test /bin/sh -c "npm run test:unit"
script:
  - sleep 1
deploy:
  provider: heroku
  app: com-stevenpilger-frontend
  api_key:
    secure: ZOtm+THuOFcRWoYvPsLh7Fqx1I3xYcqFceUcuOYTMvU51E77yvGQYvzpwnghYwPgyJbkk0PNlDoh2kwwqAimu+MePWTRIYgTkbiPtVegj0FYGdpE/hgFZm+L2tndDdYBDPx4j3aUG9+kE9LZiiKoZ15adjQ/Qk7H5ASahaQpRZlcOnB1A3FUombFOTy8eUOlGw0axLy+Err8X08K78tB7fi6mx797l7paAd8trt0rA1NlyeGqYoBQq9/scp5hLer6nc2FpHTeX+IB2j4LIm9TxwIkKxsXsJjs4SJKa4VS8AEWLqwH8wRJF+9Y1plt8il42dk6l2WQbolQQ1l00KUTAZKRzCnDLRQ5KsdMyktSUunDKO5w4LXG7IQvAjKxCKl+959pHrtbSrVMXW8jg+6SZKJLfOl2zIP4iyEUXTi+Mk6tGwuuCveFwuORGeBqepIAw7CuqnChtGFeaY6+2vG1BeopH5sfvZLObVWkAtEKVKQFUPVPyKbbCjQlT+hN6mdcnfTy16HkWNb9s/RqOw49wZFmVW0drU7K8JYW39YSVYW7LkDBqTQGshaoepPxgOLxdRklpG1Lee28X2YErRSOlMDC/V6YRb4efdTNd/8QPK4vhDyYWjUDGY2Ok9hQBGK5Yqo58Ud/aggn2HUokEoxXXIBs0gZPRRkJtvUu9Ol64=
