language: node_js
node_js:
  - lts/*
services:
  - docker
before_install:
  - docker build -t stevenpilger/frontend-test -f test.Dockerfile .
  - docker run -it --rm stevenpilger/frontend-test
script:
  - sleep 10
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
  - export REPO=$DOCKER_USERNAME/frontend
  - export TAG=`if [ “$TRAVIS_BRANCH” == “master” ]; then echo “latest”; else echo $TRAVIS_BRANCH
    ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -t $REPO:$COMMIT -f production.Dockerfile .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
deploy:
  provider: heroku
  app: stevenpilger-com
  api_key:
    secure: M/rnatUx1vxDI06GGvbE0V/c61ietj4D/m0O5q87sBxkVXciUT6gz4FVz4WctOX878UvBqioCMz3ap+2tZqbxhQsercXjAyUbRLueHK1sN5SvpBYtYSlAHPYE13Hgmg26CwXPgRkx7A4XEtx00quWbiiRv+9bMSaOpmAiBh3XQvGHtAo44soCNbNx962ugf9/pPQQcXg4YysT1/OIrM4hwz8nInRtV5JMXturLlrXAOCvEiW8Gf4kG0ef1taQ8Tuix8nPqY4aDWbrbGEExszm96vrh2J5Inokn3FJWaHLwbpK1LBxKfzBIWOjRZ0DaUa+j7aD2hYaes/QjY7SCvVm8teTWYqki7ce0RXBdtzuSZMs59deSnrEtaFdT3OzQ5fXZsUK9hIrhph2s93WPDXILGM7QnsHRYdIiAzKROQjs6jJhVn2hsIcSdmXQItCOjHRtN3BoDn+PYsLzuxnV/JNstr9fQ6UNvQl9/wt9uHOCXXUDHfo0YYuG3+X6ixkvIOBs/CHECMbcwvm2et7eaYyDBMP5t1ZWg6o6pDHPNj/BGb2lfb+bT6TSySbJHCWLofclhUUeVakQxl614Mp7s8eyppKSzoORuUAWfQUei9fzeWlY3RJwkWLzJEcUM4+oelqDdkV7e9ppOBYo4qRM7PtoQ9vJegndn3X3UpO252KrU=
